language: node_js
node_js:
    - "12"
script:
    - npm run build
before_install:
    - npm install -g firebase-tools
install:
    - npm i
after_success:
    - firebase deploy --project be-the-hero-8cf76 --token $FIREBASE_TOKEN
